export const FETCH_LANES_REQUEST = 'FETCH_LANES_REQUEST';
export const FETCH_LANES_SUCCESS = 'FETCH_LANES_SUCCESS';
export const FETCH_LANES_FAILURE = 'FETCH_LANES_FAILURE';
export const RECEIVE_LANES = 'RECEIVE_LANES';
export const SET_LANES_FILTER = 'SET_LANES_FILTER';
export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';
